core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pythagor.urls')),
    path('admin/', admin.site.urls),
]

pythagor/urls.py
from django.urls import path

from . import views

app_name = 'pythagor'
urlpatterns = [
    path('', views.index, name='index'),
    path('triangle/', views.triangle, name='triangle'),
    path('hypotenuse/', views.hypotenuse, name='hypotenuse'),
    path('person/result/', views.contact_form_result, name='result'),
    path('person/', views.contact_form, name='user_form'),
    path('person_detail/<int:pk>/', views.contact_form_detail, name='people_detail'),
    path('person/<int:pk>/', views.contact_form_edit, name='people_edit'),
    path('person_delete/<int:pk>/', views.contact_form_delete, name='people_delete'),
]

catalog/models.py
from django.db import models


class Provider(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=80)

    def __str__(self):
        return "%s provider" % self.name


class City(models.Model):
    provider = models.OneToOneField(Provider, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return "%s city" % self.name


class Product(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s product" % self.name


class Client(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    address = models.CharField(max_length=80)
    email = models.EmailField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

pythagor/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class People(models.Model):
    first_name = models.CharField('First name', max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    email = models.EmailField('Email')

    def __str__(self):
        return "%s %s %s" % (self.first_name, self.last_name, self.email)


class Log(models.Model):
    CHOICES = (
        ('CONNECT', 'CONNECT'),
        ('DELETE', 'DELETE'),
        ('GET', 'GET'),
        ('HEAD', 'HEAD'),
        ('OPTIONS', 'OPTIONS'),
        ('POST', 'POST'),
        ('PUT', 'PUT'),
    )
    path = models.CharField(max_length=255)
    method = models.CharField(max_length=7, choices=CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    status_code = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    data = models.JSONField(null=True, blank=True)

    def __str__(self):
        return "%s %s %s %s %s" % (self.path, self.method, self.timestamp, self.user, self.data)

pythagor/forms.py
from django import forms

from .models import People


class PeopleForm(forms.ModelForm):
    class Meta:
        model = People
        fields = ['first_name', 'last_name', 'email']


class Pythagor(forms.Form):
    side_a = forms.IntegerField(label='lengths of the side "a"', help_text='cm', min_value=1)
    side_b = forms.IntegerField(label='lengths of the side "b"', help_text='cm', min_value=1)

pythagor/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PeopleForm, Pythagor
from .models import People


def index(request):
    return render(request, 'pythagor/index.html')


def hypotenuse(request):
    side_c = request.GET.get('side_c', '')
    return render(request, 'pythagor/hypotenuse.html', {'side_c': side_c})


def triangle(request):
    if "ok" in request.GET:
        triangle_form = Pythagor(request.GET)
        if triangle_form.is_valid():
            side_a = triangle_form.cleaned_data['side_a']
            side_b = triangle_form.cleaned_data['side_b']
            side_c = (side_a ** 2 + side_b ** 2) ** 0.5
            redirect_url = reverse('pythagor:hypotenuse') + f'?side_c={side_c}'
            return HttpResponseRedirect(redirect_url)
    else:
        triangle_form = Pythagor()
    return render(request, 'pythagor/triangle.html', {'triangle_form': triangle_form})


def contact_form_detail(request, pk):
    obj = get_object_or_404(People, pk=pk)
    return render(request, 'pythagor/people-detail.html', {'obj': obj})


def contact_form(request):
    if request.method == 'POST':
        user_form = PeopleForm(request.POST)
        if user_form.is_valid():
            obj = user_form.save()
            return redirect('pythagor:people_detail', pk=obj.pk)
    else:
        user_form = PeopleForm()
    return render(request, 'pythagor/people.html', {'user_form': user_form})


def contact_form_result(request):
    user = People.objects.all()
    return render(request, 'pythagor/people-result.html', {"user": user})


def contact_form_edit(request, pk):
    obj = get_object_or_404(People, pk=pk)
    if request.method == 'POST':
        user_form = PeopleForm(request.POST, instance=obj)
        if user_form.is_valid():
            obj = user_form.save()
            return redirect('pythagor:people_detail', pk=obj.pk)
    else:
        user_form = PeopleForm(instance=obj)
    return render(request, 'pythagor/people-edit.html', {'user_form': user_form, 'obj': obj})


def contact_form_delete(request, pk):
    obj = get_object_or_404(People, pk=pk)
    if request.method == 'POST':
        obj.delete()
        return redirect('pythagor:result')
    return render(request, 'pythagor/people-delete.html', {'obj': obj})

templates/pythagor/hypotenuse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hypotenuse</title>
</head>
<body>
   <h1>Pythagorean theorem:</h1>
   <p>Hypotenuse: {{ side_c }} cm</p>
</body>
</html>

templates/pythagor/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle</title>
</head>
<body>
<p><a href="{% url 'pythagor:triangle' %}">Triangle</a> GET form</p>
<p><a href="{% url 'pythagor:user_form' %}">Contact Form</a> POST form</p>
<p><a href="{% url 'pythagor:result' %}">Users</a> Created users</p>
</body>
</html>

templates/pythagor/people-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
    <h1>Are you sure? Do you like delete user {{ obj }}?</h1>
    <form action="{% url 'pythagor:people_delete' pk=obj.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes">
        <a href="{% url 'pythagor:result' %}">No</a>
    </form>
</body>
</html>

templates/pythagor/people-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<h1>{{ obj }}</h1>
<a href="{% url 'pythagor:people_edit' pk=obj.pk %}">Edit</a>
<a href="{% url 'pythagor:people_delete' pk=obj.pk %}">Delete</a>
</body>
</html>

templates/pythagor/people-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
    <h1> Contact form edit - {{ obj }}</h1>
    <form action="{% url 'pythagor:people_edit' pk=obj.pk %}" method="post">
        {% csrf_token %}

        <table>
            {{ user_form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/pythagor/people-result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
    <h1>Users</h1>
    <ul>
        {% for i in user %}
        <li><a href="{% url 'pythagor:people_detail' pk=i.pk%}">{{ i }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/pythagor/people.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact form</title>
</head>
<body>
    <h1> Contact form</h1>
    <form action="{% url 'pythagor:user_form' %}" method="post">
        {% csrf_token %}

        <table>
            {{ user_form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/pythagor/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle</title>
</head>
<body>
    <h1>Pythagorean theorem:</h1>
    <form action="{% url 'pythagor:triangle' %}" method="get">
        {{ triangle_form.as_p }}
        <input type="submit" name="ok" value="Submit">
    </form>
</body>
</html>